import type { Match, Sport } from "./types"

// Datos simulados. Reemplaza estos endpoints por tu API real.
export const SPORTS: Sport[] = [
  { id: "1", name: "Fútbol", slug: "futbol", icon: "futbol", eventCount: 248 },
  { id: "2", name: "Baloncesto", slug: "baloncesto", icon: "baloncesto", eventCount: 96 },
  { id: "3", name: "Tenis", slug: "tenis", icon: "tenis", eventCount: 132 },
  { id: "4", name: "Béisbol", slug: "beisbol", icon: "beisbol", eventCount: 54 },
  { id: "5", name: "Fútbol Am.", slug: "futbol-americano", icon: "futbol-americano", eventCount: 38 },
  { id: "6", name: "Hockey", slug: "hockey", icon: "hockey", eventCount: 41 },
  { id: "7", name: "MMA", slug: "mma", icon: "mma", eventCount: 22 },
  { id: "8", name: "eSports", slug: "esports", icon: "esports", eventCount: 67 },
]

export const MATCHES: Match[] = [
  {
    id: "m1",
    sport: "futbol",
    league: "UEFA Champions League",
    startTime: new Date().toISOString(),
    isLive: true,
    minute: 63,
    home: { name: "Real Madrid", score: 2 },
    away: { name: "Manchester City", score: 1 },
    market: { home: 2.1, draw: 3.4, away: 3.05 },
    featured: true,
  },
  {
    id: "m2",
    sport: "futbol",
    league: "LaLiga",
    startTime: new Date().toISOString(),
    isLive: true,
    minute: 28,
    home: { name: "Barcelona", score: 0 },
    away: { name: "Atlético Madrid", score: 0 },
    market: { home: 1.85, draw: 3.6, away: 4.2 },
  },
  {
    id: "m3",
    sport: "futbol",
    league: "Premier League",
    startTime: new Date(Date.now() + 3600_000).toISOString(),
    isLive: false,
    home: { name: "Liverpool" },
    away: { name: "Arsenal" },
    market: { home: 2.35, draw: 3.3, away: 2.9 },
    featured: true,
  },
  {
    id: "m4",
    sport: "baloncesto",
    league: "NBA",
    startTime: new Date(Date.now() + 7200_000).toISOString(),
    isLive: false,
    home: { name: "LA Lakers" },
    away: { name: "Boston Celtics" },
    market: { home: 1.7, away: 2.2 },
    featured: true,
  },
  {
    id: "m5",
    sport: "tenis",
    league: "ATP Masters",
    startTime: new Date().toISOString(),
    isLive: true,
    minute: 0,
    home: { name: "C. Alcaraz", score: 1 },
    away: { name: "J. Sinner", score: 1 },
    market: { home: 1.9, away: 1.95 },
  },
  {
    id: "m6",
    sport: "futbol",
    league: "Serie A",
    startTime: new Date(Date.now() + 10800_000).toISOString(),
    isLive: false,
    home: { name: "Inter" },
    away: { name: "Juventus" },
    market: { home: 2.05, draw: 3.1, away: 3.8 },
  },
  {
    id: "m7",
    sport: "futbol-americano",
    league: "NFL",
    startTime: new Date(Date.now() + 14400_000).toISOString(),
    isLive: false,
    home: { name: "Chiefs" },
    away: { name: "49ers" },
    market: { home: 1.65, away: 2.3 },
  },
  {
    id: "m8",
    sport: "esports",
    league: "League of Legends - Worlds",
    startTime: new Date().toISOString(),
    isLive: true,
    minute: 0,
    home: { name: "T1", score: 1 },
    away: { name: "G2 Esports", score: 0 },
    market: { home: 1.45, away: 2.75 },
  },
]
